name: macOS Workflow

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: make all
      run: |
        clang --version
        make all
      
    - name: make all mode=debug
      run: |
        clang --version
        make all mode=debug
      
    - name: macOSBundle
      run: |
        clang --version
        make macOSBundle
      
    - name: macOSBundle mode=debug
      run: |
        clang --version
        make macOSBundle mode=debug
