name: macOS Workflow

on:
  push: 
    branches: [ "master" ]
  pull_request: 
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manually run macOS workflow'
        required: false

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: make all
      run: |
        clang --version
        make all
      
    - name: make all mode=debug
      run: |
        clang --version
        make all mode=debug
      
    - name: macOSBundle
      run: |
        clang --version
        make macOSBundle
      
    - name: macOSBundle mode=debug
      run: |
        clang --version
        make macOSBundle mode=debug
