name: Windows Workflow

on:
  push: 
    branches: [ "master" ]
  pull_request: 
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manually run Windows workflow'
        required: false

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: make all
      run: |
        g++ --version
        make all
      
    - name: make all mode=debug
      run: |
        g++ --version
        make all mode=debug
